<?php
    $sort_order = Mage::getSingleton('core/session')->getOrder();
    $comments = array();
    $lastId = 0;
?>

<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend">All Comments</h4>
    </div>
    
    <br />
    
    <div>
        <input id="delete_key" type="hidden" value="<?php echo Mage::getSingleton('adminhtml/url')->getSecretKey("adminhtml_comments","delete"); ?>" />
        <input id="last_id" type="hidden" value="<?php echo (Mage::getModel('comments/post')->getCollection()->getLastItem()->getId()+1); ?>" />
        <form method="post" action="<?php echo $this->getUrl('comments/adminhtml_comments/sort/');?>">
            <div >
                <?php $formKey = Mage::getSingleton('core/session')->getFormKey();?>
                <input name="form_key" type="hidden" value="<?php echo $formKey; ?>" />
                <?php
                    if($sort_order==null || $sort_order=="ASC") 
                    {
                        echo "<label>Сверху вниз</label><input type='radio' name='sort' value='ASC' checked />";
                        echo "<label>Знизу вверх</label><input type='radio' name='sort' value='DESC'/>";
                    }
                    else 
                    { 
                        echo "<label>Сверху вниз</label><input type='radio' name='sort' value='ASC'/>";
                        echo "<label>Знизу вверх</label><input type='radio' name='sort' value='DESC' checked />";
                    }
                ?>

                <input type="submit" id="sort_submit" value="Сортировать" />
            </div>
        </form>

        <?php

        if (Mage::getSingleton('admin/session')->isLoggedIn()) 
        {
            $userName = Mage::getSingleton('admin/session')->getUser()->getName();
        }


        if ($this->getRequest()->getModuleName()=="project")
                $project = $this->getRequest()->getParam('pr');       
        if ($this->getRequest()->getModuleName()=="tasks")
                $task = $this->getRequest()->getParam('id');

        
        if ($project != null || $project != 0)
        {
            $comments = Mage::getModel('comments/post')->getCollection();
            $comments = $comments->addFieldToFilter('project', $project)->setOrder('id', $sort_order);
        }
        if($task != null || $task != 0)
        {
            $comments = Mage::getModel('comments/post')->getCollection();
            $comments = $comments->addFieldToFilter('task',$task)->setOrder('id', $sort_order);
        }
        ?>

        <form id="post_form" method="POST" action="">        

            <?php $formKey = Mage::getSingleton('core/session')->getFormKey();?>
            
            <input name="url" id="url" type="hidden" value="<?php echo $this->getUrl('comments/adminhtml_comments/add/');?>" />
            <input name="form_key" type="hidden" value="<?php echo $formKey; ?>" />
            <input name="date" id="date" type="hidden" value="<?php echo (date("Y-m-d H:i:s")); ?>" />
            <input name="Project_id" id="Project_id" type="hidden" value="<?php echo $project; ?>" />
            <input name="Task_id" id="Task_id" type="hidden" value="<?php echo $task; ?>" />   
            <br />
            <table border = "0">
                <tr><td>Комментарий:</td></tr>
                <tr><td><input type="hidden" name="Author" id="Author" value="<?php echo $userName; ?>" /></td></tr>
                <tr><td><textarea rows="8" cols="95%" name="Comment" id="Comment"></textarea></td></tr>
                <tr><td><input type="button" id="send_submit" value="Отправить" /></td></tr>
            </table>
            
        </form>
        
    </div>

    <br />

    <div id="group_fields4" class="fieldset fieldset-wide">
        <?php
        foreach ($comments as $item):?>
            <div id="<?php echo ("comment".$item['id']); ?>" class="comment_block">
                <table>
                            <tr>
                                <td colspan='2'><b><?=$item['author']?></b></td>
                            </tr>
                            <tr>
                                <td colspan='2'>
                                    <div id="<?='comm_'.$item['id']?>">
                                        <?=$item['comment']?>
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td><?=$item['date']?></td>
                                <td>                    
                                    <?php if ($userName == $item['author']): ?>
                                        <div id="edit_panel">
                                            <a href="#" onclick="show_edit(<?=$item['id']?>);" id="edit_link">Edit</a>
                                            <a href="#" onclick="delete_link(<?=$item['id']?>);">Delete</a>
                                        </div>
                                    <? endif; ?>
                                </td>
                            </tr>
                </table>
                <br />
            </div>
                
        <? endforeach; ?>

    </div>

    <br />

    <div id="edit_block">
        <a href="javascript:hide_edit();">Закрыть</a>
        <br />
        <form id="edit_comment_form" method="POST" action="<?php echo $this->getUrl('comments/adminhtml_comments/edit/');?>">
            <?php $formKey = Mage::getSingleton('core/session')->getFormKey();?>
            <input name="date" id="date" type="hidden" value="<?php echo (date("Y-m-d H:i:s")); ?>" />
            <input name="form_key" type="hidden" value="<?php echo $formKey; ?>" />
            <input name="Project_id" type="hidden" value="<?php echo $project; ?>" />
            <input name="id" id='id' type="hidden" value="" />
            <input name="Task_id" type="hidden" value="<?php echo $task; ?>" /> 
            <input type="hidden" name="Author" value="<?php echo $userName; ?>" />
            Комментарий: 
            <br />
            <textarea rows="8" cols="85%" id="edit_comment" name="Comment"></textarea>
            <br />
            <input type="submit" id="save" value="Сохранить" />
        </form>
    </div>
    
</div>

<div id="mask"></div>

