<?php 

	// $item = Mage::getModel('comments/post')
 //                    ->getCollection()
 //                    ->addAttributeToSort('id', 'desc')
 //                    ->limit(1);
echo "ПРИВЕЕЕЕЕЕЕЕЕТ";
?>                                

<!-- <table id="comment_list">
    <tr>
        <td collspan='2 '><b><?=$item['author']?></b></td>
    </tr>
    <tr>
        <td collspan='2'>
            <div id="<?='comm_'.$item['id']?>">
                                    <?=$item['comment']?>
            </div>
        </td>
        </tr>
        <tr>
            <td><?=$item['date']?></td>
            <td>
                
            <?php if ($name == $item['author']): ?>
                <div id="edit_panel">
                    <a href="#" onclick="show_edit(<?=$item['id']?>);" id="edit_link">Edit</a> 
                    &nbsp 
                    <a href="<?php echo $this->getUrl('comments/adminhtml_comments/delete/id/'.$item['id']);?>">Delete</a></div>
            <? endif; ?>
                     
            </td>
        </tr>
</table> -->